spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.99.100:49161:xe
    username: roland
    password: Roland99
  liquibase:
    enabled: true
    change-log: classpath:output_dbchangelog.xml
#apikey: ...
#  jpa:
#    show-sql: true
#
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create