spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.99.100:49161:xe
    username: system
    password: oracle
  liquibase:
    enabled: true
    change-log: classpath:output_dbchangelog.xml
#  jpa:
#    show-sql: true
#
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create